"""included is_principal, description and poster_function fields in posters

Revision ID: 5716caecc491
Revises: 92f7935229d4
Create Date: 2020-06-26 13:02:37.234153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5716caecc491'
down_revision = '92f7935229d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('description', sa.String(), nullable=True))
    op.add_column('section', sa.Column('is_principal', sa.Boolean(), nullable=True))
    op.add_column('section', sa.Column('poster_function', sa.String(), nullable=True))
    op.drop_column('section', 'poster_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('poster_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('section', 'poster_function')
    op.drop_column('section', 'is_principal')
    op.drop_column('section', 'description')
    # ### end Alembic commands ###
