"""included movie description field

Revision ID: 315b018db42a
Revises: e79feefdff90
Create Date: 2020-06-03 19:06:07.184805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '315b018db42a'
down_revision = 'e79feefdff90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'description')
    # ### end Alembic commands ###
