"""Included movie ratings fields

Revision ID: 03904d907bf1
Revises: d72227819bcc
Create Date: 2020-05-28 19:43:04.612192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '03904d907bf1'
down_revision = 'd72227819bcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('movie', sa.Column('vote_count', sa.Integer(), nullable=True))

    op.execute(
        """
        UPDATE movie M
        set rating = R.avg_rating, vote_count = R.vote_count
        FROM (SELECT rating.movie as movie_id, count(*) as vote_count, avg(rating) as avg_rating 
                FROM rating group by rating.movie) R
        WHERE M.id = R.movie_id
        """
    )
    op.execute(
        """
        UPDATE movie
        set rating = 0, vote_count = 0
        WHERE vote_count isnull
        """
    )

    op.alter_column('movie', 'rating',
                    existing_type=postgresql.DOUBLE_PRECISION(precision=5),
                    nullable=False,
                    server_default='0')
    op.alter_column('movie', 'vote_count',
                    existing_type=sa.INTEGER(),
                    nullable=False,
                    server_default='1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'vote_count')
    op.drop_column('movie', 'rating')
    # ### end Alembic commands ###
