"""included API-KEY in requests

Revision ID: e79feefdff90
Revises: 1436c7623396
Create Date: 2020-05-31 17:12:27.681107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e79feefdff90'
down_revision = '1436c7623396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('with_token', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'with_token')
    # ### end Alembic commands ###
