"""removing user-movie restrictions for POC purposes

Revision ID: 05d210b1d5be
Revises: 5d8f377f0cbf
Create Date: 2020-07-10 13:01:29.238554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05d210b1d5be'
down_revision = '5d8f377f0cbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('id', sa.Integer(), nullable=False, server_default='1'))
    op.drop_constraint(op.f('rating_pkey'), table_name='rating')
    op.alter_column('rating', 'movie',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rating', 'user',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_index(op.f('ix_rating_id'), 'rating', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rating_id'), table_name='rating')
    op.alter_column('rating', 'user',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rating', 'movie',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('rating', 'id')
    op.create_index(op.f('rating_pkey'), 'rating', ['user', 'movie'], unique=False)
    # ### end Alembic commands ###
