"""Included genre poster path field

Revision ID: 0f3359d9596d
Revises: 315b018db42a
Create Date: 2020-06-04 19:15:35.315908

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0f3359d9596d'
down_revision = '315b018db42a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genre', sa.Column('poster_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('genre', 'poster_path')
    # ### end Alembic commands ###
