"""Changed movie genres field to string

Revision ID: 62d078d55e88
Revises: 03904d907bf1
Create Date: 2020-05-29 15:59:35.986131

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '62d078d55e88'
down_revision = '03904d907bf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('genres', sa.String(), server_default='', nullable=False))
    op.execute("""
        UPDATE movie M
        set genres = G.genres
        FROM (SELECT movie, string_agg(genre, '|') as genres from movie_genre group by movie) G
        WHERE M.id = G.movie
    """)

    op.drop_table('movie_genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_genre',
                    sa.Column('movie', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['genre'], ['genre.id'], name='movie_genre_genre_fkey'),
                    sa.ForeignKeyConstraint(['movie'], ['movie.id'], name='movie_genre_movie_fkey'),
                    sa.PrimaryKeyConstraint('movie', 'genre', name='movie_genre_pkey')
                    )

    op.execute("""
        INSERT INTO movie_genre(movie, genre)
        SELECT id, unnest(string_to_array(genres, '|')) as genre FROM movie
    """)

    op.drop_column('movie', 'genres')
    # ### end Alembic commands ###
