"""created sections

Revision ID: 92f7935229d4
Revises: eb75a9f2a14d
Create Date: 2020-06-24 18:03:49.577032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92f7935229d4'
down_revision = 'eb75a9f2a14d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('poster_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_section_id'), 'section', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_section_id'), table_name='section')
    op.drop_table('section')
    # ### end Alembic commands ###
